/**
* Tables designed to recieve data from old DB
*/ 

CREATE TABLE fsdb.z_import_fs_users (
	UserId int,
	UserName text,
	Email text,
	Password text,
	DateCreated text,
	LastActivityDate text,
	LoginAttempts text,
	GuidId text,
	Code text,
	PhotosLimit text,
	LastChecked text,
	Revisit text,
	LastUpdateDate text,
	LastSystemEmail text,
	DateApproved text,
	DateDeactivated text,
	IPAddress text,
	MessagesBlockedDate text,
	AdminNotes text,
	AccountLevel text,
	IsSystem text,
	IsActive text,
	PackageId text,
	PackageExpiration text,
	PendingApproval text,
	IsDeleted text,
	Status text,
	ModeratorStatus text,
	EmailConfirmed text,
	PasswordHash text,
	SecurityStamp text,
	PhoneNumber text,
	Discriminator text,
	IdentityUser_Id text,
	LockoutEndDateUtc text,
	LockoutEnabled text,
	PhoneNumberConfirmed text,
	TwoFactorEnabled text,
	AccessFailedCount text,
	TimeZone text,
	UserType text,
	Version text
) 